### ISSUE TITLE
"new" games on gog.com are importing as unknown games with "new" in the title.

### ISSUE THREAD

**Issue by avgjoe** [ssokolow/itad_importer#21] opened 2015-11-14 14:34 UTC
The problem is really gog.com having the "new" label on a game in my library. I assume you are really busy and this is a trivial matter, but it would be nice if the script could ignore the "new" in the title on import. I emailed gog support but haven't received a reply on how to remove this. Some games I have installed still have the "new" label, some games i have not even installed don't have it. Thanks for your hard work, I get a lot of use out of this script.

![screenshot-www gog com 2015-11-14 08-19-32](https://cloud.githubusercontent.com/assets/20477/11164014/1e79254a-8aaa-11e5-8d3a-f4907441874c.png)
![screenshot-isthereanydeal com 2015-11-14 08-20-34](https://cloud.githubusercontent.com/assets/20477/11164018/22aa6962-8aaa-11e5-8dfc-7bd45a4bb358.png)

**Comment by ssokolow** [comment] 2015-11-14 15:24
Duplicate of issue #19 and already fixed in commit 9b06751c8a5d256af2b8609bddc8ea7d5202cd76 (9 days ago).

Your browser isn't downloading updated versions for some reason, so force an update by reinstalling.

**Closed by ssokolow** 2015-11-14 15:24 UTC
