### ISSUE TITLE
Humble Bundle no longer works

### ISSUE THREAD

**Issue by Asgraf** [ssokolow/itad_importer#10] opened 2015-04-15 18:19 UTC
Recent changes in layout broke compatibility

**Comment by ssokolow** [comment] 2015-04-16 05:07
Thanks for letting me know. Recent Humble Bundles haven't interested me so I didn't have reason to notice.

I'll take a look A.S.A.P.

**Comment by ssokolow** [comment] 2015-04-16 08:39
While, indeed, they did rework things (I now have to set NoScript to let Google stuff through to make the game listing load), the Humble Indie Bundle 14 still exports correctly here.

Which bundle are you experiencing the problem with and can you test on some other bundles to be certain it's not bundle specific?

(Also, keep in mind that, by design, the script doesn't export entries that just provide a key for another store. (eg. It won't dump Steam-only games because those are supposed to be handled by ITAD's built-in Steam sync support)

**Comment by zookae** [comment] 2015-06-06 18:37
I think the problem is the library interface itself is different from before.

**Comment by ssokolow** [comment] 2015-06-06 22:03
As I said to Asgraf, it still works perfectly for me. If I can't reproduce the problem, I can't diagnose it and write a solution.

Where are you experiencing the problem? (eg. "Humble Foo Bundle, download page")

**Comment by tfedor** [comment] 2015-06-06 22:10
I bet he means that it doesn't work for library page https://www.humblebundle.com/home/library (there's no link to export to ITAD), so you can't import whole library at once. You can still import individual bundles from Purchases tab though.

**Comment by ssokolow** [comment] 2015-06-06 22:15
Ahh. That'd do it. That change wasn't exposed to me when Asgraf initially reported the problem (maybe I was on the wrong side of some A/B testing) and I forgot to re-check it this time.

I'll try to get a fix pushed once I've had breakfast.

**Comment by ssokolow** [comment] 2015-06-06 23:09
Hmm. This is going to be trickier than I thought. The new Backbone-based design doesn't exactly expose much to the global scope and, at the time onDOMReady and onLoad are called, the spot I want to put the button doesn't exist yet.

**Comment by ssokolow** [comment] 2015-06-07 04:48
OK, I've got it sort-of working, but I'm going to need to come up with a fancier solution because, in its current form, it can't recognize Steam-only entries and omit them.

**Comment by ssokolow** [comment] 2015-06-08 06:00
Given the uncertainty with Desura's parent company having entered bankruptcy protection, I'm going to need to focus my free time over the next little while on hedging my bets by contacting the developers of the various games there and asking if I could have a key on another service (typically Humble or IndieGameStand).

As such, here's a branch with the code I've got so far.

https://github.com/ssokolow/itad_importer/tree/humble-fix

It works if you don't mind it importing Steam-only entries as "owned on Humble" but I have a strict No-DRM policy, so I still consider that too broken to update the master branch.

**Comment by ssokolow** [comment] 2015-06-13 04:39
For anyone who needs more help using the `humble-fix` branch, I replied to a [misfiled question](https://github.com/ssokolow/lgogd_uri/issues/20) with explanatory screenshots.

**Comment by ssokolow** [comment] 2015-07-11 12:01
I've merged the `humble-fix` branch into master and mentioned the current shortcoming in the README.

Overzealous import is better than no import since many Steam users won't mind if a game is listed as owned on Humble when it's only a Steam key and I don't want to have to bother with resolving merge conflicts after a major refactor of the code to add support for paginated import.

**Closed by ssokolow** 2015-07-11 12:01 UTC
Labels: bug, confirmed, in progress
